// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package model

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonC7c61ac9DecodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel(in *jlexer.Lexer, out *UserURLList) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(UserURLList, 0, 2)
			} else {
				*out = UserURLList{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 UserURLItem
			if in.IsNull() {
				in.Skip()
			} else {
				(v1).UnmarshalEasyJSON(in)
			}
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC7c61ac9EncodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel(out *jwriter.Writer, in UserURLList) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			(v3).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v UserURLList) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC7c61ac9EncodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UserURLList) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC7c61ac9EncodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UserURLList) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC7c61ac9DecodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UserURLList) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC7c61ac9DecodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel(l, v)
}
func easyjsonC7c61ac9DecodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel1(in *jlexer.Lexer, out *UserURLItem) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "short_url":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ShortURL = string(in.String())
			}
		case "original_url":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OriginalURL = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC7c61ac9EncodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel1(out *jwriter.Writer, in UserURLItem) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"short_url\":"
		out.RawString(prefix[1:])
		out.String(string(in.ShortURL))
	}
	{
		const prefix string = ",\"original_url\":"
		out.RawString(prefix)
		out.String(string(in.OriginalURL))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UserURLItem) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC7c61ac9EncodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UserURLItem) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC7c61ac9EncodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UserURLItem) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC7c61ac9DecodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UserURLItem) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC7c61ac9DecodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel1(l, v)
}
func easyjsonC7c61ac9DecodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel2(in *jlexer.Lexer, out *ShortenResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "result":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Result = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC7c61ac9EncodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel2(out *jwriter.Writer, in ShortenResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"result\":"
		out.RawString(prefix[1:])
		out.String(string(in.Result))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ShortenResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC7c61ac9EncodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ShortenResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC7c61ac9EncodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ShortenResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC7c61ac9DecodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ShortenResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC7c61ac9DecodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel2(l, v)
}
func easyjsonC7c61ac9DecodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel3(in *jlexer.Lexer, out *ShortenRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "url":
			if in.IsNull() {
				in.Skip()
			} else {
				out.URL = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC7c61ac9EncodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel3(out *jwriter.Writer, in ShortenRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"url\":"
		out.RawString(prefix[1:])
		out.String(string(in.URL))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ShortenRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC7c61ac9EncodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ShortenRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC7c61ac9EncodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ShortenRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC7c61ac9DecodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ShortenRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC7c61ac9DecodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel3(l, v)
}
func easyjsonC7c61ac9DecodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel4(in *jlexer.Lexer, out *DeleteUserURLsRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(DeleteUserURLsRequest, 0, 4)
			} else {
				*out = DeleteUserURLsRequest{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v4 string
			if in.IsNull() {
				in.Skip()
			} else {
				v4 = string(in.String())
			}
			*out = append(*out, v4)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC7c61ac9EncodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel4(out *jwriter.Writer, in DeleteUserURLsRequest) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v5, v6 := range in {
			if v5 > 0 {
				out.RawByte(',')
			}
			out.String(string(v6))
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v DeleteUserURLsRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC7c61ac9EncodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DeleteUserURLsRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC7c61ac9EncodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *DeleteUserURLsRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC7c61ac9DecodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DeleteUserURLsRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC7c61ac9DecodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel4(l, v)
}
func easyjsonC7c61ac9DecodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel5(in *jlexer.Lexer, out *BatchShortenResponseItem) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "correlation_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CorrelationID = string(in.String())
			}
		case "short_url":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ShortURL = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC7c61ac9EncodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel5(out *jwriter.Writer, in BatchShortenResponseItem) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"correlation_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.CorrelationID))
	}
	{
		const prefix string = ",\"short_url\":"
		out.RawString(prefix)
		out.String(string(in.ShortURL))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BatchShortenResponseItem) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC7c61ac9EncodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BatchShortenResponseItem) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC7c61ac9EncodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BatchShortenResponseItem) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC7c61ac9DecodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BatchShortenResponseItem) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC7c61ac9DecodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel5(l, v)
}
func easyjsonC7c61ac9DecodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel6(in *jlexer.Lexer, out *BatchShortenResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(BatchShortenResponse, 0, 2)
			} else {
				*out = BatchShortenResponse{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v7 BatchShortenResponseItem
			if in.IsNull() {
				in.Skip()
			} else {
				(v7).UnmarshalEasyJSON(in)
			}
			*out = append(*out, v7)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC7c61ac9EncodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel6(out *jwriter.Writer, in BatchShortenResponse) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v8, v9 := range in {
			if v8 > 0 {
				out.RawByte(',')
			}
			(v9).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v BatchShortenResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC7c61ac9EncodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BatchShortenResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC7c61ac9EncodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BatchShortenResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC7c61ac9DecodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BatchShortenResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC7c61ac9DecodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel6(l, v)
}
func easyjsonC7c61ac9DecodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel7(in *jlexer.Lexer, out *BatchShortenRequestItem) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "correlation_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CorrelationID = string(in.String())
			}
		case "original_url":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OriginalURL = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC7c61ac9EncodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel7(out *jwriter.Writer, in BatchShortenRequestItem) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"correlation_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.CorrelationID))
	}
	{
		const prefix string = ",\"original_url\":"
		out.RawString(prefix)
		out.String(string(in.OriginalURL))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BatchShortenRequestItem) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC7c61ac9EncodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BatchShortenRequestItem) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC7c61ac9EncodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BatchShortenRequestItem) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC7c61ac9DecodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BatchShortenRequestItem) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC7c61ac9DecodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel7(l, v)
}
func easyjsonC7c61ac9DecodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel8(in *jlexer.Lexer, out *BatchShortenRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(BatchShortenRequest, 0, 2)
			} else {
				*out = BatchShortenRequest{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v10 BatchShortenRequestItem
			if in.IsNull() {
				in.Skip()
			} else {
				(v10).UnmarshalEasyJSON(in)
			}
			*out = append(*out, v10)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC7c61ac9EncodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel8(out *jwriter.Writer, in BatchShortenRequest) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v11, v12 := range in {
			if v11 > 0 {
				out.RawByte(',')
			}
			(v12).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v BatchShortenRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC7c61ac9EncodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BatchShortenRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC7c61ac9EncodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BatchShortenRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC7c61ac9DecodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BatchShortenRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC7c61ac9DecodeGithubComHimmelSparkGoMusthaveShortenerGitInternalModel8(l, v)
}
